#!/usr/bin/env python3
"""
WfFormat to DISSECT-CF-Fog XML Converter
=========================================

Converts WfCommons WfFormat JSON workflows to DISSECT-CF-Fog XML format.

Usage:
    python3 wfformat_to_dissect_converter.py input.json output.xml
"""

import json
import os
import sys
import xml.etree.ElementTree as ET
from xml.dom import minidom
from pathlib import Path
from typing import Dict, List, Any

# Default output directory: ../demo/WORKFLOW_examples relative to this script
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_DEFAULT_OUTPUT_DIR = os.path.join(_SCRIPT_DIR, "..", "demo", "WORKFLOW_examples")


class WfFormatToDissectConverter:
    """Converts WfFormat JSON to DISSECT-CF-Fog XML."""

    def __init__(self, json_path: str):
        """Initialize converter with JSON workflow file."""
        with open(json_path, 'r') as f:
            self.workflow_data = json.load(f)

        self.workflow_spec = self.workflow_data['workflow']['specification']
        self.workflow_exec = self.workflow_data['workflow'].get('execution', {})
        self.tasks_map = {task['id']: task for task in self.workflow_spec['tasks']}

        # Build fileId -> sizeInBytes map from specification.files (generated by WfCommons)
        self.files_map = {
            f['id']: f['sizeInBytes']
            for f in self.workflow_spec.get('files', [])
        }

    def convert(self) -> ET.Element:
        """Convert to DISSECT-CF-Fog XML format."""
        # Create root element
        root = ET.Element('adag')
        root.set('name', self.workflow_data.get('name', 'Workflow'))
        root.set('repeat', '1')

        # Add comment with metadata
        comment_text = f" Generated from WfFormat by wfformat_to_dissect_converter.py "
        comment = ET.Comment(comment_text)
        root.append(comment)

        # Convert each task
        for task in self.workflow_spec['tasks']:
            job_elem = self._convert_task(task)
            root.append(job_elem)

        return root

    def _convert_task(self, task: Dict[str, Any]) -> ET.Element:
        """Convert a single task to <job> element."""
        job = ET.Element('job')
        job.set('id', task['id'])

        # Get runtime (from execution data if available, otherwise use synthetic)
        runtime = self._get_task_runtime(task['id'])
        job.set('runtime', f"{runtime:.2f}")

        # Add geo-location if available (optional in DISSECT-CF-Fog)
        # WfFormat doesn't have this, so we skip it

        # Add input requirements (compute).
        # amount = in-degree (number of parents). The Java executor decrements
        # this counter on each parent completion and only schedules the job
        # when it reaches 0, so fan-in nodes must wait for ALL parents.
        parent_count = len(task.get('parents', []))
        input_elem = ET.SubElement(job, 'uses')
        input_elem.set('link', 'input')
        input_elem.set('type', 'compute')
        input_elem.set('amount', str(parent_count))

        # Add outputs (data dependencies to children)
        for child_id in task.get('children', []):
            output_elem = ET.SubElement(job, 'uses')
            output_elem.set('link', 'output')
            output_elem.set('id', child_id)
            output_elem.set('type', 'data')

            # Calculate data size (if files exist, use them; otherwise synthetic)
            size = self._get_data_size(task['id'], child_id)
            output_elem.set('size', str(size))

        return job

    def _get_task_runtime(self, task_id: str) -> float:
        """Get task runtime from execution data or generate synthetic value."""
        if self.workflow_exec.get('tasks'):
            exec_tasks = {t['id']: t for t in self.workflow_exec['tasks']}
            if task_id in exec_tasks and 'runtimeInSeconds' in exec_tasks[task_id]:
                return exec_tasks[task_id]['runtimeInSeconds']

        # Generate synthetic runtime (10-60 seconds)
        import random
        random.seed(hash(task_id))
        return random.uniform(10.0, 60.0)

    # Realistic file size ranges derived from WfCommons task_type_stats.json traces
    TASK_PAIR_SIZES = {
        ("split_fasta", "blastall"):   (6,     2_015),    # .fasta segments
        ("blastall",    "cat_blast"):  (5,     17_952),   # .out result files
        ("blastall",    "cat"):        (0,     0),        # .err files (empty)
        ("fastqSplit",  "filterContams"): (100, 5_000),   # epigenomics
        ("filterContams", "fastqc"):   (100,   5_000),
        ("filterContams", "mapMerge"): (1_000, 50_000),
    }

    # Shared-file size threshold: files larger than this are likely common
    # databases/binaries (not actual data transfers between tasks), e.g. the
    # 4.5 GB "nt" BLAST database.
    _SHARED_FILE_THRESHOLD = 50 * 1_024 * 1_024  # 50 MB

    def _get_data_size(self, parent_id: str, child_id: str) -> int:
        """Get data transfer size between tasks.

        Priority:
        1. specification.files sizes from the JSON (real WfCommons-generated data)
           — sums the child task's inputFiles sizes, excluding shared files > 50 MB
        2. Task-name-pair based ranges from WfCommons task_type_stats.json
        3. Fallback synthetic size (1KB - 1MB)
        """
        import random
        parent_task = self.tasks_map.get(parent_id, {})
        child_task  = self.tasks_map.get(child_id,  {})

        # 1. Use real file sizes from specification.files
        if self.files_map:
            input_sizes = [
                self.files_map[fid]
                for fid in child_task.get('inputFiles', [])
                if fid in self.files_map
                and self.files_map[fid] < self._SHARED_FILE_THRESHOLD
            ]
            if input_sizes:
                return sum(input_sizes)

        # 2. Task-name-pair based realistic sizes
        parent_name = parent_task.get('name', '')
        child_name  = child_task.get('name', '')
        pair = (parent_name, child_name)

        if pair in self.TASK_PAIR_SIZES:
            lo, hi = self.TASK_PAIR_SIZES[pair]
            if lo == hi:
                return lo
            random.seed(hash(parent_id + child_id))
            return random.randint(lo, hi)

        # 3. Fallback: synthetic size (1KB - 1MB)
        random.seed(hash(parent_id + child_id))
        return random.randint(1_024, 1_048_576)

    def write_xml(self, output_path: str, prettify: bool = True):
        """Write converted XML to file."""
        root = self.convert()

        if prettify:
            # Pretty print
            xml_str = minidom.parseString(
                ET.tostring(root, encoding='unicode')
            ).toprettyxml(indent="  ")

            # Remove extra blank lines
            xml_str = '\n'.join([line for line in xml_str.split('\n') if line.strip()])

            with open(output_path, 'w') as f:
                f.write(xml_str)
        else:
            tree = ET.ElementTree(root)
            tree.write(output_path, encoding='unicode', xml_declaration=True)

        print(f"✓ Converted workflow saved to: {output_path}")
        print(f"  - Tasks: {len(self.workflow_spec['tasks'])}")


def main():
    """Main entry point."""
    if len(sys.argv) < 2 or len(sys.argv) > 3:
        print("Usage: python3 wfformat_to_dissect_converter.py INPUT.json [OUTPUT.xml]")
        print("\nThe output is always placed in the WORKFLOW_examples directory.")
        print("If OUTPUT.xml is omitted, the input filename with .xml extension is used.")
        print("\nExample:")
        print("  python3 wfformat_to_dissect_converter.py blast_workflow.json")
        print("  python3 wfformat_to_dissect_converter.py blast_workflow.json blast_converted.xml")
        sys.exit(1)

    input_json = sys.argv[1]

    if not Path(input_json).exists():
        print(f"Error: Input file not found: {input_json}")
        sys.exit(1)

    # Resolve output into WORKFLOW_examples
    if len(sys.argv) == 3:
        out_filename = os.path.basename(sys.argv[2])
    else:
        out_filename = Path(input_json).stem + "_converted.xml"
    os.makedirs(_DEFAULT_OUTPUT_DIR, exist_ok=True)
    output_xml = os.path.join(_DEFAULT_OUTPUT_DIR, out_filename)

    try:
        converter = WfFormatToDissectConverter(input_json)
        converter.write_xml(output_xml)
        print(f"\n✓ Conversion successful!")
    except Exception as e:
        print(f"Error during conversion: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
